# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Composite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('suffix', models.CharField(max_length=2)),
                ('scenario', models.CharField(max_length=30)),
                ('weigth', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Indices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=30)),
                ('unit', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='composite',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Indices'),
        ),
    ]
