# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20160629_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='composite',
            name='cod',
            field=models.CharField(default='VALE', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indices',
            name='cod',
            field=models.CharField(default='vale', max_length=30),
            preserve_default=False,
        ),
    ]
