# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20160629_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=30)),
                ('unit', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='composite',
            name='index',
        ),
        migrations.RemoveField(
            model_name='composite',
            name='weight',
        ),
        migrations.DeleteModel(
            name='Indices',
        ),
        migrations.AddField(
            model_name='membership',
            name='composite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Composite'),
        ),
        migrations.AddField(
            model_name='membership',
            name='indice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Indice'),
        ),
        migrations.AddField(
            model_name='composite',
            name='members',
            field=models.ManyToManyField(through='dashboard.Membership', to='dashboard.Indice'),
        ),
    ]
