# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20160629_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('indice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Indice')),
            ],
        ),
    ]
