# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivaidoso', '0002_auto_20160926_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='cep1',
            field=models.TextField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estado',
            name='cep2',
            field=models.TextField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estado',
            name='desc_estado',
            field=models.TextField(max_length=72),
        ),
    ]
