# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('vivaidoso', '0003_auto_20160926_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140)),
                ('nat_juridica', models.CharField(max_length=60)),
                ('horario_visita', models.CharField(max_length=60)),
                ('lot_maxima', models.CharField(max_length=60)),
                ('apresentacao', tinymce.models.HTMLField()),
                ('servicos', tinymce.models.HTMLField()),
                ('admissao', tinymce.models.HTMLField()),
                ('atividades', tinymce.models.HTMLField()),
                ('localizacao', tinymce.models.HTMLField()),
            ],
        ),
    ]
