# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vivaidoso', '0004_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='bairro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vivaidoso.Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='descricao',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
