# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vivaidoso', '0005_auto_20161017_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('file', models.FileField(upload_to=b'images/%Y/%m/%d')),
            ],
        ),
    ]
