# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vivaidoso', '0006_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vivaidoso.Empresa'),
            preserve_default=False,
        ),
    ]
