# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vivaidoso', '0009_empresa_faixa_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='dependencia',
            field=models.CharField(choices=[(1, b'Grau 1'), (2, b'Grau 2'), (3, b'Grau 3')], default=1, max_length=1),
        ),
        migrations.AddField(
            model_name='empresa',
            name='leitos',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, b'Individual'), (2, b'Duplo'), (3, b'Triplo'), (4, b'Qu\xc3\xa1druplo')], default=1, max_length=7),
        ),
        migrations.AddField(
            model_name='empresa',
            name='servicos_incl',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, b'Nenhum'), (2, b'Cuidador individual 24hrs'), (3, b'Fisioterapeuta'), (4, b'Terapia Ocupacional'), (5, b'Psic\xc3\xb3logo'), (6, b'Acompanhamento m\xc3\xa9dico')], default=1, max_length=11),
        ),
        migrations.AddField(
            model_name='empresa',
            name='sexo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, b'Masculino'), (2, b'Feminino'), (3, b'Misto')], default=1, max_length=5),
        ),
    ]
